//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feiyingx.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string ProjectMainImage { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<System.DateTime> ProjectDate { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectFeatures { get; set; }
        public string ProjectTech { get; set; }
        public string FeatureMainImage { get; set; }
        public string FeatureTitle { get; set; }
        public string FeatureDescription { get; set; }
        public string ProjectUrl { get; set; }
        public string ProjectUrlText { get; set; }
        public bool IsFeatured { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string FeatureCssTheme { get; set; }
    }
}
