//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feiyingx.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PositionTitle { get; set; }
        public string LinkedIn { get; set; }
        public string CompanyName { get; set; }
        public string CompanyUrl { get; set; }
        public string CssClass { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime RecommendationDate { get; set; }
        public string Message { get; set; }
    }
}
